Reservoir separate transforms
ai2cm/fv3net pull request #2308
Opened 2023-08-11 00:40 UTC by AnnaKwa

This PR adds the ability to load separate transforms for input/output/hybrid variable sets (or fit different standard normalization transforms if not specified). These are organized in a new `TransformerGroup` class that replaces the single `autoencoder` attribute of the reservoir models. 

If the output variable list is different from the input variable list, the training script will use the output transformer when preparing the paired output set.

Added public API:
- The previous single `autoencoder_path` parameter in the `ReservoirTrainingConfig` is now replaced by a `TransformerConfig` which contains optional paths for input, output, and hybrid transformers

Refactored public API:
- Aforementioned API change breaks old configs
- Breaks old model loading, since models now dump and load a `TransformerGroup` instead of a single autoencoder 

 

- [ x] Tests added

2023-08-11 20:20 UTC, frodre requested changes
Thanks @AnnaKwa, I think there's a few changes necessary before this one is ready.

One essential change is that the transformers may have different `z_feature_size` dimensions, so the rank divider may not work for different transformer outputs due to the shape checking.  Perhaps adding a method to the rank divider that would generate a new rank divider object  (for hybrid/outputs) used for batch processing based on the `n_latent_dims` of the transformer.  Have a divider for inputs/outputs/(maybe hybrids).  Along the lines of this [method](https://github.com/ai2cm/fv3net/blob/b12a2d00bd74cc35c94b3b906dc9c374da1f3f95/external/fv3fit/fv3fit/reservoir/domain2.py#L127).  On one hand it's good to have rigorous checks that the shapes line up, but again trailing features are making things more difficult at implementation time.  (Which I believe was the motivation for removing all `z` info in one of your earlier PRs)

Additionally, the current structure of transformer groups was a bit hard to follow because there are delayed decisions being made about whether a transformer is reused or not.  I would rather see something where we have the training set up which transformers are used for what variable group, but once instantiated and saved, the group attributes will always point to a transformer.  You can use store some context in the class so saving/loading doesn't duplicate, but it's really not that resource intensive to just save everything.  That would remove logic checks about which one to use outside of that group class and the training init function.  Let me know what you think, I'm very open to context or suggestions on this.

2023-08-11 20:20 UTC, frodre commented on external/fv3fit/fv3fit/reservoir/train.py
> +        # If the output variables differ from inputs, use the transformer specific
I think we need separate arguments for X and y rank divider and transformers with the processing function to simplify the training code.

2023-08-12 00:13 UTC, AnnaKwa commented on external/fv3fit/fv3fit/reservoir/train.py
> +        # If the output variables differ from inputs, use the transformer specific
I opted to simplify the function formerly known as `process_batch_Xy_data` to just operate on a single set of variables, and use the overlap of the rank_divider provided to determine whether to trim halo points.

2023-08-14 23:14 UTC, AnnaKwa commented on external/fv3fit/fv3fit/reservoir/train.py
> +        )
Changed the `TransformerGroup` to require the `output` arg, and still have an optional `hybrid` arg. All logic about using the input transformer in place of another is removed from the `TransformerGroup`.

2023-08-14 23:17 UTC, AnnaKwa commented on external/fv3fit/fv3fit/reservoir/train.py
> +        # If the output variables differ from inputs, use the transformer specific
To allow this function to work on input/output/hybrid data individually, it was necessary to add another arg `trim_halo`. I found this to be the clearest way to specify whether the halo points needed to be excluded. Another arg is not ideal, but IMO more clear than how it was before where first/second items returned were with/without overlap points.

2023-08-15 20:53 UTC, frodre approved these changes
Looks good!  Thanks for the updates, I think the notion of which encoders are used and when is very clear now.  One minor thing to adjust in the training code that sets up the transform group, but otherwise ready to go.

2023-08-15 20:53 UTC, frodre commented on external/fv3fit/fv3fit/reservoir/train.py
> +    else:
If `output` is in `transformers`, should defer to the loaded transformer.   Only set the output transformer to input if nothing specified and variables sets are equivalent.  Can be fixed by moving the conditional on variable sets into the `not in transformers` block.

2023-08-15 20:53 UTC, frodre commented on external/fv3fit/fv3fit/reservoir/train.py
> +    if "hybrid" not in transformers and hyperparameters.hybrid_variables is not None:
Same situation as `output` transformer above.  Move the `hybrid_variables` check into the `not in transformers` block.

2023-08-15 20:53 UTC, frodre commented on external/fv3fit/fv3fit/reservoir/train.py
> +        # If the output variables differ from inputs, use the transformer specific
Awesome, very good solution to the issue!

2023-08-15 20:53 UTC, frodre commented on external/fv3fit/fv3fit/reservoir/transformers/transformer.py
> +
`Reloadable` is now redundant in the `DoNothingAutoencoder` subclass instance and can be removed.

2023-08-15 20:53 UTC, frodre commented on external/fv3fit/fv3fit/reservoir/utils.py
> +    The rank
Leftover in docstring

2023-08-15 22:29 UTC, merged